---

- hosts: all
  become: true
  tasks:

    - name: remove apache2 package & php package
      package:
        name: 
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: absent
        update_cache: yes
      when: ansible_distribution in ["Ubuntu","Debian"]